### ISSUE TITLE
Overriding LOCAL_LANG values outdated

### ISSUE THREAD

**Issue by pniederlag** [TYPO3-Documentation/TYPO3CMS-Reference-InsideTypo3#1] opened 2014-07-10 08:40 UTC
Documentation says to use 'XLLfile' like so:

```
$TYPO3_CONF_VARS['BE']['XLLfile']['EXT:lang/locallang_core.xml']='typo3conf/llor_test.xml';
```

This seems outdated, http://docs.typo3.org/typo3cms/CoreApiReference/Internationalization/Translation/Index.html#custom-translations is more up to date.

Either update in TYPO3CMS-Reference-InsideTypo3 or set a Link to CoreApiReference

**Comment by fsuter** [comment] 2014-07-12 10:18
Inside TYPO3 is so desperately outdated. I guess this is one of my main sore point regarding TYPO3 documentation. Nobody never had time to tackle that manual.

So, yes, you're right. However I'm not sure it's very useful to update a single line in a manual that needs to be completely overhauled. Your call, however. If you insist, we'll do it (or you can try your hand at submitting a pull request, it's now really easy to edit official TYPO3 documentation via Github).

**Comment by pniederlag** [comment] 2014-07-12 10:42
I already started on the PR... I could not find a pointer or example on how to crosslink to another manual however that's when I stopped proceeding.;( Wasn't there some "power of REST for TYPO3 doc editors" or something like that?

**Comment by fsuter** [comment] 2014-07-12 10:54
I see :-(

There's a primer written by Xavier: http://docs.typo3.org/typo3cms/drafts/github/xperseguers/RstPrimer/

but it's not quite complete on the cross-linking topic. In your case, you want to do something like:

```
:ref:`see Core APIs <t3api:xliff-translating-custom>`
```

where "t3api" is the code by which the rendered version of the Core APIs manual is referenced in the Sphinx project settings and "xliff-translating-custom" is the target label inside Core APIs for cross-referencing to the precise chapter.

HTH

**Comment by xperseguers** [comment] 2014-07-14 07:29
Hi, in fact the most up-to-date documentation is in the manual of EXT:sphinx itself, in the "Writers Manual" part: http://docs.typo3.org/typo3cms/extensions/sphinx/WritersManual/DocsTypo3Org/Index.html#docs-typo3-org-crosslink

As a very advanced user (in fact more a sysadmin willing to cross-link virtually to anything), there's another chapter with technical details on the Sphinx cross-link mechanism: http://docs.typo3.org/typo3cms/extensions/sphinx/AdvancedUsersManual/AdvancedCrossLinks/Index.html

I'm not sure where is the best place to put such documentation. The primer could get everything but in the end it was meant at letting you get up to speed quickly. But I thought of EXT:sphinx as a "must have" anyway, that's why I took long hours to structure the manual from different user perspective. I don't know if the problem is to have the information somewhere else (as user are more and more NOT reading any documentation/manual prior to work on something, even if properly structured), or ensure it gets better indexed by Google and others.

Any suggestion is appreciated of course.

**Comment by sypets** [comment] 2017-12-08 09:22
Can we close this one now as the Localization chapter (https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-InsideTypo3/blame/latest/Documentation/CoreArchitecture/Localization/Index.rst) has been updated?

P.S. My commit had nothing to do with this issue. I used `#1` accidentally.

**Closed as completed** 2018-04-28 14:44 UTC
